name: 'Upload artifacts to Dropbox'
description: 'Uploads a folder from GitHub Actions into Dropbox.'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  folder:
    description: 'The folder in Dropbox to upload the file.'
    required: true
  path:
    description: 'Path in the current repository.'
    required: true
runs:
  using: "composite"
  steps:
    - id: action
      shell: bash
      run: |
        curl -sSL "https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh" -o ./.dropbox_uploader.sh
        echo 'f65fa50b80ef93a0e635078fc52601f56ace2c979cf031aa49b899d1d4f76707  ./.dropbox_uploader.sh' | sha256sum --check --status 
        chmod +x ./.dropbox_uploader.sh
        ./.dropbox_uploader.sh upload ${{ inputs.path }} ${{ inputs.folder }}